deploy:
  runs-on: ubuntu-latest
  env:
      HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
  steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
            heroku_api_key: ${{ secrets.HEROKU_API_TOKEN }}
            heroku_app_name: ${{ secrets.HEROKU_APP }}
            heroku_email: ${{ secrets.EMAIL }}